# Generated by Django 4.2.5 on 2023-09-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
    ]
