# Generated by Django 4.2.5 on 2023-09-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yourmodel',
            table='socialschema',
        ),
    ]
