# Generated by Django 4.2.5 on 2023-09-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_yourmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
